// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AgentConfigStatus {
    "platform": string;
    "provider"?: string;
    "targetProvider"?: string;
    "configured": boolean;
    "matchesCurrentPort": boolean;
    "needsUpdate": boolean;
    "currentBaseUrl": string;
    "targetBaseUrl": string;
    "configPath": string;
    "authPath"?: string;
    "hasState": boolean;
    "lastError"?: string;

    /** Creates a new AgentConfigStatus instance. */
    constructor($$source: Partial<AgentConfigStatus> = {}) {
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("configured" in $$source)) {
            this["configured"] = false;
        }
        if (!("matchesCurrentPort" in $$source)) {
            this["matchesCurrentPort"] = false;
        }
        if (!("needsUpdate" in $$source)) {
            this["needsUpdate"] = false;
        }
        if (!("currentBaseUrl" in $$source)) {
            this["currentBaseUrl"] = "";
        }
        if (!("targetBaseUrl" in $$source)) {
            this["targetBaseUrl"] = "";
        }
        if (!("configPath" in $$source)) {
            this["configPath"] = "";
        }
        if (!("hasState" in $$source)) {
            this["hasState"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentConfigStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentConfigStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentConfigStatus($$parsedSource as Partial<AgentConfigStatus>);
    }
}

export class ApplyAgentConfigRequest {
    "platform": string;
    "provider"?: string;
    "apiKey"?: string;
    "baseUrl"?: string;

    /** Creates a new ApplyAgentConfigRequest instance. */
    constructor($$source: Partial<ApplyAgentConfigRequest> = {}) {
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplyAgentConfigRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplyAgentConfigRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplyAgentConfigRequest($$parsedSource as Partial<ApplyAgentConfigRequest>);
    }
}

export class ConfigDiffResult {
    "files": FileDiff[];

    /** Creates a new ConfigDiffResult instance. */
    constructor($$source: Partial<ConfigDiffResult> = {}) {
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigDiffResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigDiffResult {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        return new ConfigDiffResult($$parsedSource as Partial<ConfigDiffResult>);
    }
}

export class DiffLine {
    /**
     * "context" | "added" | "removed"
     */
    "type": string;
    "content": string;

    /** Creates a new DiffLine instance. */
    constructor($$source: Partial<DiffLine> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffLine instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffLine {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffLine($$parsedSource as Partial<DiffLine>);
    }
}

export class FileDiff {
    "path": string;

    /**
     * "modify" | "create" | "delete"
     */
    "action": string;
    "lines": DiffLine[];

    /** Creates a new FileDiff instance. */
    constructor($$source: Partial<FileDiff> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("lines" in $$source)) {
            this["lines"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): FileDiff {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField2_0($$parsedSource["lines"]);
        }
        return new FileDiff($$parsedSource as Partial<FileDiff>);
    }
}

export class ProviderKeyAsset {
    "provider": string;
    "apiKey": string;
    "baseUrl"?: string;
    "planId"?: string;
    "usages"?: string[];

    /** Creates a new ProviderKeyAsset instance. */
    constructor($$source: Partial<ProviderKeyAsset> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderKeyAsset instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderKeyAsset {
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usages" in $$parsedSource) {
            $$parsedSource["usages"] = $$createField4_0($$parsedSource["usages"]);
        }
        return new ProviderKeyAsset($$parsedSource as Partial<ProviderKeyAsset>);
    }
}

// Private type creation functions
const $$createType0 = FileDiff.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = DiffLine.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
