// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "./internal/backend/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as configservice$0 from "./internal/configservice/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyAgentConfig(req: configservice$0.ApplyAgentConfigRequest): $CancellablePromise<void> {
    return $Call.ByID(1194974726, req);
}

export function GetAgentConfigStatus(platform: string): $CancellablePromise<configservice$0.AgentConfigStatus> {
    return $Call.ByID(3013260948, platform).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetAutostartStatus(): $CancellablePromise<boolean> {
    return $Call.ByID(1022089850);
}

export function GetEnvFile(): $CancellablePromise<$models.EnvFileState> {
    return $Call.ByID(4130444060).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetLogs(): $CancellablePromise<string[]> {
    return $Call.ByID(1688970508).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetProxyAccessKey(): $CancellablePromise<string> {
    return $Call.ByID(355938326);
}

export function GetStatus(): $CancellablePromise<backend$0.Status> {
    return $Call.ByID(2036427713).then(($result: any) => {
        return $$createType3($result);
    });
}

export function OpenWebUIInBrowser(): $CancellablePromise<void> {
    return $Call.ByID(2011844568);
}

export function RestartService(): $CancellablePromise<void> {
    return $Call.ByID(194936479);
}

export function RestoreAgentConfig(platform: string): $CancellablePromise<void> {
    return $Call.ByID(3544811620, platform);
}

export function SaveEnvFile(content: string): $CancellablePromise<void> {
    return $Call.ByID(4266218857, content);
}

export function SetAutostart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3109129572, enabled);
}

export function ShowAgentTab(): $CancellablePromise<void> {
    return $Call.ByID(978526812);
}

export function ShowStatusTab(): $CancellablePromise<void> {
    return $Call.ByID(1026910485);
}

export function ShowWebUITab(): $CancellablePromise<void> {
    return $Call.ByID(1839858715);
}

export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(3879395531);
}

export function StartService(): $CancellablePromise<void> {
    return $Call.ByID(220274594);
}

export function StopService(): $CancellablePromise<void> {
    return $Call.ByID(2326025444);
}

// Private type creation functions
const $$createType0 = configservice$0.AgentConfigStatus.createFrom;
const $$createType1 = $models.EnvFileState.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = backend$0.Status.createFrom;
