// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class EnvFileState {
    "path": string;
    "content": string;
    "exists": boolean;

    /** Creates a new EnvFileState instance. */
    constructor($$source: Partial<EnvFileState> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvFileState instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvFileState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvFileState($$parsedSource as Partial<EnvFileState>);
    }
}

/**
 * LanguagePreference 描述桌面语言最终选择和原始系统语言。
 */
export class LanguagePreference {
    "locale": string;
    "manual": boolean;
    "systemLocale": string;

    /** Creates a new LanguagePreference instance. */
    constructor($$source: Partial<LanguagePreference> = {}) {
        if (!("locale" in $$source)) {
            this["locale"] = "";
        }
        if (!("manual" in $$source)) {
            this["manual"] = false;
        }
        if (!("systemLocale" in $$source)) {
            this["systemLocale"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LanguagePreference instance from a string or object.
     */
    static createFrom($$source: any = {}): LanguagePreference {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LanguagePreference($$parsedSource as Partial<LanguagePreference>);
    }
}

export class VersionInfo {
    "version": string;
    "buildTime": string;
    "gitCommit": string;
    "distribution": string;

    /** Creates a new VersionInfo instance. */
    constructor($$source: Partial<VersionInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("buildTime" in $$source)) {
            this["buildTime"] = "";
        }
        if (!("gitCommit" in $$source)) {
            this["gitCommit"] = "";
        }
        if (!("distribution" in $$source)) {
            this["distribution"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): VersionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionInfo($$parsedSource as Partial<VersionInfo>);
    }
}
